const STORAGE_KEY = 'jabras-portal-language';
let currentLanguage = localStorage.getItem(STORAGE_KEY) || 'pt';
let activeModule = 'dashboard';

const ICON_DATA = `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 90"><path fill="#2b76c8" d="M8 72h24c12 0 18-5 21-18l7-34c2-9 7-14 16-14h10L76 53 61 37l-6 29c-3 14-12 22-27 22H8z"/><circle cx="92" cy="9" r="7" fill="#ef3439"/></svg>`)} `;

const messages = {
  pt: {
    dashboard: 'Dashboard', employees: 'Funcionários', attendance: 'Ponto', leave: '有休 / Férias', reports: 'Relatórios', payslips: 'Holerites', dormitory: 'Dormitórios', settings: 'Configurações', portal: 'Portal Administrativo', menu: 'MENU PRINCIPAL', overview: 'Visão geral da operação', search: 'Pesquisar no portal...', admin: 'Administrador', eyebrow: 'PORTAL ADMINISTRATIVO', greeting: 'Boa tarde', intro: 'Acompanhe as principais informações da Jabras Neo.', newLeave: '＋ Nova solicitação de 有休', activeEmployees: 'Funcionários ativos', activeEmployeesNote: '+4 neste mês', pendingLeave: '有休 pendentes', pendingLeaveNote: '3 revisões aguardando', approvedToday: 'Aprovadas hoje', approvedTodayNote: '32 dias autorizados', absentToday: 'Ausentes hoje', absentTodayNote: 'Em 4 locais de trabalho', requests: 'SOLICITAÇÕES', recentRequests: 'Solicitações recentes', viewAll: 'Ver todas →', employee: 'Funcionário', workplace: 'Local', period: 'Período', status: 'Status', pending: 'Em análise', approved: 'Aprovada', review: 'Revisão', calendar: 'CALENDÁRIO', upcomingAbsences: 'Próximas ausências', open: 'Abrir →', days2: '2 dias de 有休', day1: '1 dia de 有休', days3: '3 dias de 有休', halfDay: 'Meio período', modulePreparing: 'Módulo em preparação', moduleReady: 'A estrutura visual está pronta. Este módulo será desenvolvido nas próximas etapas.', backDashboard: 'Voltar ao dashboard', language: 'Português'
  },
  ja: {
    dashboard: 'ダッシュボード', employees: '社員', attendance: '勤怠', leave: '有休', reports: 'レポート', payslips: '給与明細', dormitory: '寮管理', settings: '設定', portal: '管理ポータル', menu: 'メインメニュー', overview: '業務全体の概要', search: 'ポータル内を検索...', admin: '管理者', eyebrow: '管理ポータル', greeting: 'こんにちは', intro: 'ジャブラスネオの主要情報を確認できます。', newLeave: '＋ 有休を申請', activeEmployees: '在籍社員', activeEmployeesNote: '今月 +4名', pendingLeave: '有休承認待ち', pendingLeaveNote: '修正依頼 3件', approvedToday: '本日の承認', approvedTodayNote: '承認済み 32日', absentToday: '本日の休暇者', absentTodayNote: '4事業所', requests: '申請', recentRequests: '最近の申請', viewAll: 'すべて表示 →', employee: '社員', workplace: '配属先', period: '期間', status: 'ステータス', pending: '確認中', approved: '承認済み', review: '修正依頼', calendar: 'カレンダー', upcomingAbsences: '今後の休暇予定', open: '開く →', days2: '有休 2日', day1: '有休 1日', days3: '有休 3日', halfDay: '半日', modulePreparing: '準備中の機能', moduleReady: '画面構成は準備済みです。この機能は次の段階で開発します。', backDashboard: 'ダッシュボードへ戻る', language: '日本語'
  }
};

const t = key => messages[currentLanguage]?.[key] ?? messages.pt[key] ?? key;
const moduleDefinitions = [['dashboard','⌂'],['employees','♙'],['attendance','◷'],['leave','休'],['reports','▤'],['payslips','¥'],['dormitory','⌂'],['settings','⚙']];
const requests = [
  { initials:'CS', name:'Carlos Silva', workplace:'岡崎', period:'05–06 ago.', status:'pending' },
  { initials:'AS', name:'Ana Souza', workplace:'花園', period:'08 ago.', status:'approved' },
  { initials:'PS', name:'Pedro Santos', workplace:'関東', period:'12–14 ago.', status:'review' },
  { initials:'MT', name:'Mariana Tanaka', workplace:'豊橋', period:'18 ago.', status:'pending' }
];

function languageSwitcher(){return `<div class="jn-lang"><button class="jn-lang-btn" type="button" aria-expanded="false">🌐 <span>${t('language')}</span> ▾</button><div class="jn-lang-menu" hidden><button class="jn-lang-opt ${currentLanguage==='pt'?'active':''}" data-lang="pt">Português</button><button class="jn-lang-opt ${currentLanguage==='ja'?'active':''}" data-lang="ja">日本語</button></div></div>`;}
function sidebar(){return `<aside class="sidebar"><div class="brand-block"><img src="${ICON_DATA}" class="brand-icon" alt="Jabras Neo" /><div class="brand-copy"><strong>JABRAS NEO</strong><span>${t('portal')}</span></div></div><div class="nav-label">${t('menu')}</div><nav>${moduleDefinitions.map(([id,icon])=>`<button class="nav-item ${activeModule===id?'active':''}" data-module="${id}"><span class="nav-icon">${icon}</span><span>${t(id)}</span></button>`).join('')}</nav><div class="sidebar-footer">株式会社ジャブラスネオ<br><span>JABRAS NEO</span></div></aside>`;}
function header(title,subtitle){return `<header class="topbar"><div class="topbar-title"><h1>${title}</h1><p>${subtitle}</p></div><div class="topbar-actions"><div class="search-box"><span>⌕</span><input placeholder="${t('search')}" /></div><button class="icon-btn" aria-label="Notificações">♢<span class="notification-dot"></span></button>${languageSwitcher()}<div class="user-block"><div class="avatar">VF</div><div><strong>Vinicius</strong><span>${t('admin')}</span></div></div></div></header>`;}
function stat(icon,label,value,note){return `<article class="card stat"><div class="stat-top"><span class="stat-icon">${icon}</span><span class="stat-label">${label}</span></div><b>${value}</b><small>${note}</small></article>`;}
function event(day,month,name,detail){return `<div class="event"><div class="event-date"><strong>${day}</strong>${month}</div><div><h4>${name}</h4><p>${detail}</p></div></div>`;}
function dashboard(){return `${header(t('dashboard'),t('overview'))}<main class="content"><section class="page-heading"><div><span class="eyebrow">${t('eyebrow')}</span><h2>${t('greeting')}</h2><p>${t('intro')}</p></div><button class="primary-btn" data-module="leave">${t('newLeave')}</button></section><section class="stats">${stat('♙',t('activeEmployees'),'186',t('activeEmployeesNote'))}${stat('休',t('pendingLeave'),'12',t('pendingLeaveNote'))}${stat('✓',t('approvedToday'),'8',t('approvedTodayNote'))}${stat('◷',t('absentToday'),'6',t('absentTodayNote'))}</section><section class="dashboard-grid"><div class="card panel"><div class="panel-head"><div><span class="section-kicker">${t('requests')}</span><h3>${t('recentRequests')}</h3></div><button class="link-btn" data-module="leave">${t('viewAll')}</button></div><div class="table-wrap"><table class="table"><thead><tr><th>${t('employee')}</th><th>${t('workplace')}</th><th>${t('period')}</th><th>${t('status')}</th></tr></thead><tbody>${requests.map(r=>`<tr><td><div class="employee"><div class="mini-avatar">${r.initials}</div><strong>${r.name}</strong></div></td><td><span class="workplace">${r.workplace}</span></td><td>${r.period}</td><td><span class="badge ${r.status}">${t(r.status)}</span></td></tr>`).join('')}</tbody></table></div></div><div class="card panel"><div class="panel-head"><div><span class="section-kicker">${t('calendar')}</span><h3>${t('upcomingAbsences')}</h3></div><button class="link-btn" data-module="leave">${t('open')}</button></div><div class="timeline">${event('05','AGO','Carlos Silva',`岡崎 • ${t('days2')}`)}${event('08','AGO','Ana Souza',`花園 • ${t('day1')}`)}${event('12','AGO','Pedro Santos',`関東 • ${t('days3')}`)}${event('18','AGO','Mariana Tanaka',`豊橋 • ${t('halfDay')}`)}</div></div></section></main>`;}
function placeholder(id){const item=moduleDefinitions.find(m=>m[0]===id);return `${header(t(id),t('modulePreparing'))}<main class="content"><section class="card module-placeholder"><div class="placeholder-icon">${item?.[1]||'◻'}</div><h2>${t(id)}</h2><p>${t('moduleReady')}</p><button class="primary-btn" data-module="dashboard">${t('backDashboard')}</button></section></main>`;}
function bindEvents(){document.querySelectorAll('[data-module]').forEach(button=>button.addEventListener('click',()=>{activeModule=button.dataset.module;render();}));const langButton=document.querySelector('.jn-lang-btn');const langMenu=document.querySelector('.jn-lang-menu');langButton?.addEventListener('click',event=>{event.stopPropagation();langMenu.hidden=!langMenu.hidden;langButton.setAttribute('aria-expanded',String(!langMenu.hidden));});document.querySelectorAll('[data-lang]').forEach(option=>option.addEventListener('click',()=>{currentLanguage=option.dataset.lang;localStorage.setItem(STORAGE_KEY,currentLanguage);render();}));}
function render(){document.documentElement.lang=currentLanguage==='ja'?'ja':'pt-BR';document.querySelector('#app').innerHTML=`<div class="app-shell">${sidebar()}<div class="main">${activeModule==='dashboard'?dashboard():placeholder(activeModule)}</div></div>`;bindEvents();}
document.addEventListener('click',()=>{const menu=document.querySelector('.jn-lang-menu');if(menu)menu.hidden=true;});
render();