(()=>{
const exact={
'Dashboard':'ダッシュボード','Funcionários':'社員管理','Funcionário':'社員','Cadastros Mestres':'マスタ管理','Dados':'基本情報','Equipamentos':'備品','Serviços':'ライフライン','Dados pessoais':'個人情報','Trabalho':'勤務情報','Moradia':'住居情報','Documentos':'書類','Seguros':'保険','Pagamento':'給与・振込','Veículo':'車両','Dependentes':'扶養家族','Histórico':'履歴','Nome':'名称','Capacidade':'定員','Endereço':'住所','Estacionamento':'駐車場','Aluguel da empresa':'会社家賃','Encargo':'管理費','Valor pago pelo funcionário':'社員負担額','Valor por pessoa':'1人あたり負担額','Sim':'あり','Não':'なし','Ligado':'契約中','Desligado':'解約済み','Ligação':'契約日','Desligamento':'解約日','Observações / 立ち合い / 預り金':'備考／立ち合い／預り金','Endereço da última conta':'最終請求書の送付先','Salvar':'保存','Fechar':'閉じる','Cancelar':'キャンセル','Criar':'登録','Editar':'編集','Excluir':'削除','Pesquisar':'検索','Adicionar':'追加','Novo':'新規登録','Ativo':'在籍','Inativo':'退職','Bancos':'銀行','Agências':'支店','Banco':'銀行','Agência':'支店','Cliente':'取引先','Clientes':'取引先','Fábrica':'工場','Fábricas':'工場','Setor':'部署','Setores':'部署','Turnos':'班','班 / Turnos':'班','Status':'状態','Data':'日付','Observações':'備考','Imóvel':'社宅','Imóveis':'社宅','Documentos pessoais':'個人書類','Tipo':'種類','Responsável':'担当者','Conta':'口座','Gerenciar':'管理','Cliente e Fábrica':'取引先・工場','Clientes e Fábricas':'取引先・工場','Clientes e estrutura':'取引先・工場構成','Bancos e agências':'銀行・支店','Tipos de documento':'書類種別','HOMOLOGAÇÃO':'検証環境','Homologação V1':'検証環境 V1','Cadastros organizados por área e por hierarquia.':'カテゴリ・階層別のマスタ設定','Banco → Agências':'銀行 → 支店','Cliente → Fábricas → Setores / 班':'取引先 → 工場 → 部署／班','Abrir 社宅管理':'社宅管理を開く','cadastrados':'件登録','cadastrado':'件登録','Salvo':'保存しました','Verifique os dados':'入力内容をご確認ください','Novo Setor':'部署を追加','Nova Agência':'支店を追加','Novo Banco':'銀行を追加','Novo Cliente':'取引先を追加','Nova Fábrica':'工場を追加','Código':'コード','Código do banco':'銀行コード','Código da agência':'支店コード','Nome do banco':'銀行名','Nome da agência':'支店名','Nenhum':'なし','Nenhuma':'なし','Nenhum equipamento.':'備品は登録されていません。'};
const phrases=[
['Observações (opcional)','備考（任意）'],['Endereço da última conta (opcional)','最終請求書の送付先（任意）'],['Pesquisar por nome, 〒 ou endereço...','名称・〒・住所で検索...'],['Informe o nome do apartamento.','社宅名を入力してください。'],['Lista de imóveis cadastrados.','登録済み社宅一覧'],['Nenhum apartamento encontrado.','該当する社宅がありません。'],['Clique para abrir a ficha completa.','クリックして社員情報を開きます。'],['Homologação funcional com dados gravados neste navegador.','このブラウザに保存されたデータで動作確認できます。'],['Ao marcar o serviço como Desligado, a data de desligamento é obrigatória.','「解約済み」にする場合は、解約日の入力が必須です。'],['não foi desligado.','の解約日が入力されていません。'],['não foram desligados.','の解約日が入力されていません。'],['data de desligamento','解約日'],['Informe a data de desligamento de ','次の解約日を入力してください：'],[' antes de salvar.',''],['fábrica(s)','工場'],['clientes','取引先'],['fábricas','工場'],['setores','部署'],['agências','支店'],['bancos','銀行'],['cadastrados','件登録'],['cadastrado','件登録'],['Vinculado à fábrica ','工場：'],['Para cadastrar em outra fábrica, feche e use o botão da fábrica desejada.','別の工場へ登録する場合は、この画面を閉じて対象工場の追加ボタンから登録してください。'],['Para cadastrar em outra fábrica, feche e use o botão da fábrica desejada','別の工場へ登録する場合は、この画面を閉じて対象工場の追加ボタンから登録してください'],['Fábrica vinculada:','対象工場：']];
function tr(s){if(!s)return s;const t=s.trim();if(exact[t])return s.replace(t,exact[t]);let o=s;for(const [a,b] of phrases)o=o.split(a).join(b);return o.replace(/\+ Novo funcionário/g,'+ 社員を新規登録').replace(/\+ Novo cliente/g,'+ 取引先を追加').replace(/\+ Nova fábrica/g,'+ 工場を追加').replace(/\+ Setor/g,'+ 部署を追加').replace(/\+ 班/g,'+ 班を追加').replace(/Editar fábrica/g,'工場を編集').replace(/Editar cliente/g,'取引先を編集').replace(/Novo 社宅/g,'社宅を新規登録').replace(/Novo Setor/g,'部署を追加').replace(/Novo Banco/g,'銀行を追加').replace(/Nova Agência/g,'支店を追加').replace(/Clientes e Fábricas/g,'取引先・工場').replace(/\/ Turnos/g,'').replace(/Turnos/g,'班');}
function translate(root=document.body){document.documentElement.lang='ja';document.title='Jabras Neo — 管理システム（検証環境）';if(!root)return;const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT),a=[];while(w.nextNode())a.push(w.currentNode);a.forEach(n=>{if(!n.parentElement?.matches('script,style')){const x=tr(n.nodeValue);if(x!==n.nodeValue)n.nodeValue=x}});root.querySelectorAll?.('[placeholder]').forEach(e=>e.placeholder=tr(e.placeholder));root.querySelectorAll?.('[title]').forEach(e=>e.title=tr(e.title));root.querySelectorAll?.('[aria-label]').forEach(e=>e.setAttribute('aria-label',tr(e.getAttribute('aria-label'))));}
function addCss(){if(document.getElementById('jaUiFixCss'))return;const st=document.createElement('style');st.id='jaUiFixCss';st.textContent=`.radio-row{gap:22px!important;flex-wrap:nowrap!important}.radio-row label{white-space:nowrap!important;word-break:keep-all!important;min-width:max-content!important;display:inline-flex!important;align-items:center!important}.radio-row label input{flex:0 0 auto!important}.nav button{white-space:nowrap}.parent-lock{line-height:1.55}.tabs button{white-space:nowrap!important}`;document.head.appendChild(st)}
function patch(){
 addCss();
 if(typeof window.systemNotice==='function'&&!window.__jaNotice){const old=window.systemNotice;window.systemNotice=(m,t='入力内容をご確認ください')=>old(tr(String(m)),tr(String(t)));window.__jaNotice=1}
 if(typeof window.openDorm==='function'&&!window.__jaDorm){const old=window.openDorm;window.openDorm=function(id,tab='dados'){old(id,tab);setTimeout(()=>{translate();if(tab==='equip')ensureAppliances(id)},0)};window.__jaDorm=1}
}
function getDb(){try{return typeof db!=='undefined'?db:window.db}catch{return window.db}}
function ensureAppliances(id){const data=getDb();const d=data?.dorms?.find(x=>x.id===id);const body=typeof drawerBody!=='undefined'?drawerBody:window.drawerBody;if(!d||!body)return;let box=body.querySelector('#jaApplianceManager');if(box)return;box=document.createElement('div');box.id='jaApplianceManager';box.className='panel';box.style.marginTop='14px';const persist=()=>{try{typeof save==='function'?save():window.save?.()}catch{window.save?.()}};const render=()=>{box.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:12px"><div><h3 style="margin:0">備品管理</h3><div class="muted" style="font-size:12px;margin-top:4px">社宅内の貸与備品と管理番号を登録します。</div></div><button class="btn primary" id="jaAddAppliance">+ 備品を追加</button></div><div>${(d.appliances||[]).map((a,i)=>`<div style="display:grid;grid-template-columns:minmax(160px,1fr) minmax(140px,1fr) auto;gap:10px;align-items:end;margin-bottom:10px"><div class="field" style="margin:0"><label>備品</label><input data-ai="${i}" data-k="type" value="${a.type||''}" placeholder="例：冷蔵庫"></div><div class="field" style="margin:0"><label>管理番号</label><input data-ai="${i}" data-k="control" value="${a.control||''}" placeholder="例：G005"></div><button class="btn danger" data-del="${i}">削除</button></div>`).join('')||'<div class="muted" style="padding:8px 0">備品はまだ登録されていません。</div>'}</div>`;box.querySelector('#jaAddAppliance').onclick=()=>{d.appliances=d.appliances||[];d.appliances.push({type:'',control:''});persist();render()};box.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{d.appliances.splice(Number(b.dataset.del),1);persist();render()});box.querySelectorAll('[data-ai]').forEach(inp=>inp.onchange=()=>{d.appliances[Number(inp.dataset.ai)][inp.dataset.k]=inp.value;persist()});};render();body.appendChild(box)}
let q=false;const schedule=()=>{if(q)return;q=true;requestAnimationFrame(()=>{q=false;patch();translate()})};new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true,characterData:true});setInterval(()=>{patch();translate()},400);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',schedule);else schedule();
})();