(()=>{
const textMap=new Map(Object.entries({
'Dashboard':'ダッシュボード','Funcionários':'社員管理','Funcionário':'社員','Férias / 有休':'有休管理','Avaliações':'評価管理','Desligamentos':'退職管理','Alojamentos':'社宅管理','Veículos':'車両管理','Cadastros Mestres':'マスタ管理','Usuários':'ユーザー管理','Configurações':'設定','Dados':'基本情報','Equipamentos':'備品','Serviços':'ライフライン','Nome':'名称','Capacidade':'定員','Endereço':'住所','Estacionamento':'駐車場','Aluguel da empresa':'会社家賃','Encargo':'管理費','Valor pago pelo funcionário':'社員負担額','Valor por pessoa':'1人あたり負担額','Sim':'あり','Não':'なし','Ligado':'契約中','Desligado':'解約済み','Ligação':'契約日','Desligamento':'解約日','Observações / 立ち合い / 預り金':'備考／立ち合い／預り金','Endereço da última conta':'最終請求書の送付先','Salvar':'保存','Fechar':'閉じる','Cancelar':'キャンセル','Criar':'登録','Editar':'編集','Excluir':'削除','Pesquisar':'検索','Novo 社宅':'社宅を新規登録','Novo cliente':'取引先を新規登録','Nova fábrica':'工場を新規登録','Editar cliente':'取引先を編集','Clientes e Fábricas':'取引先・工場','Bancos':'銀行','Agências':'支店','Documentos':'書類','Cliente e Fábrica':'取引先・工場','Setores':'部署','Nenhum':'なし','Nenhuma fábrica.':'工場は登録されていません。','Nenhum cliente.':'取引先は登録されていません。','Salvo':'保存しました','Verifique os dados':'入力内容をご確認ください','Imóvel':'物件','Valor funcionário':'社員負担額','Lista de imóveis cadastrados.':'登録済み社宅一覧','Nenhum apartamento encontrado.':'該当する社宅がありません。','Dados pessoais':'個人情報','Trabalho':'勤務情報','Moradia':'住居情報','Pagamento':'給与・振込','Dependentes':'扶養家族','Histórico':'履歴','Documentos pessoais':'個人書類','Cliente':'取引先','Fábrica':'工場','Setor':'部署','Responsável':'担当者','Banco':'銀行','Agência':'支店','Conta':'口座','Tipo':'種類','Status':'状態','Data':'日付','Observações':'備考','Adicionar':'追加','Novo':'新規登録','Ativo':'在籍','Inativo':'退職'}));
const phraseMap=[
['Pesquisar por nome, 〒 ou endereço...','名称・〒・住所で検索...'],['Informe o nome do apartamento.','社宅名を入力してください。'],['está marcado como Desligado, mas a data de desligamento não foi informada.','が「解約済み」になっていますが、解約日が入力されていません。'],['estão marcados como Desligado, mas a data de desligamento não foi informada.','が「解約済み」になっていますが、解約日が入力されていません。'],['Informe a data de desligamento de ','次の解約日を入力してください：'],[' antes de salvar.',''],['fábrica(s)','工場'],['Nenhum apartamento encontrado.','該当する社宅がありません。'],['Vinculado à fábrica ','工場に紐付いています：'],['Para cadastrar em outra fábrica, feche e use o botão da fábrica desejada.','別の工場へ登録する場合は、この画面を閉じて対象工場の追加ボタンから登録してください。']
];
function translateString(s){if(!s)return s;const trimmed=s.trim();if(textMap.has(trimmed)){const lead=s.match(/^\s*/)?.[0]||'',tail=s.match(/\s*$/)?.[0]||'';return lead+textMap.get(trimmed)+tail}let out=s;for(const [a,b] of phraseMap)out=out.split(a).join(b);out=out.replace(/\+ Novo cliente/g,'+ 取引先を追加').replace(/\+ Nova fábrica/g,'+ 工場を追加').replace(/\+ Setor/g,'+ 部署を追加').replace(/\+ 班/g,'+ 班を追加').replace(/Editar fábrica/g,'工場を編集').replace(/Editar cliente/g,'取引先を編集');return out}
function translate(root=document.body){if(!root)return;document.documentElement.lang='ja';document.title='Jabras Neo — 管理システム（検証環境）';const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const n of nodes){if(n.parentElement?.matches('script,style'))continue;const t=translateString(n.nodeValue);if(t!==n.nodeValue)n.nodeValue=t}root.querySelectorAll?.('[placeholder]').forEach(el=>{el.placeholder=translateString(el.placeholder)});root.querySelectorAll?.('[title]').forEach(el=>{el.title=translateString(el.title)});root.querySelectorAll?.('[aria-label]').forEach(el=>{el.setAttribute('aria-label',translateString(el.getAttribute('aria-label')))});}
let queued=false;const schedule=()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;translate()})};new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>translate());else translate();
})();