(()=>{
 const wait=()=>{if(typeof openEmployee!=='function'||typeof db==='undefined'||typeof by!=='function'||typeof save!=='function')return setTimeout(wait,60);if(window.__hmlWorkFinalV2)return;window.__hmlWorkFinalV2=1;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const uid=p=>p+'_'+Date.now()+'_'+Math.random().toString(36).slice(2,6);
 const opt=(arr,sel)=>`<option value="__add__">＋ 新規登録</option><option value="">—</option>`+arr.map(x=>`<option value="${x.id}" ${x.id===sel?'selected':''}>${esc(x.name||'')}</option>`).join('');
 const fmtDate=s=>{const d=new Date(s);return Number.isNaN(d.getTime())?String(s||'').slice(0,10).replaceAll('-','/'):`${d.getFullYear()}/${String(d.getMonth()+1).padStart(2,'0')}/${String(d.getDate()).padStart(2,'0')}`};
 const nameOf=(arr,id)=>arr.find(x=>x.id===id)?.name||'—';
 function masters(){db.workContactMasters=db.workContactMasters||{commanders:[],complaints:[]};db.workContactMasters.commanders=db.workContactMasters.commanders||[];db.workContactMasters.complaints=db.workContactMasters.complaints||[];return db.workContactMasters}
 function contactWidget(id,value,type){const a=masters()[type];return `<div class="wc-wrap" data-wc-type="${type}"><input id="${id}" class="wc-input" autocomplete="off" value="${esc(value||'')}" placeholder="選択または新規入力"><button type="button" class="wc-arrow">▾</button><div class="wc-list">${a.length?a.map((x,i)=>`<div class="wc-row"><button type="button" class="wc-pick" data-i="${i}">${esc(x)}</button><button type="button" class="wc-del" data-i="${i}">×</button></div>`).join(''):'<div class="wc-empty">登録済みデータはありません。</div>'}</div></div>`}
 function bindContacts(){document.querySelectorAll('.wc-wrap').forEach(w=>{const type=w.dataset.wcType,box=w.querySelector('.wc-list'),inp=w.querySelector('input');w.querySelector('.wc-arrow').onclick=e=>{e.stopPropagation();box.classList.toggle('open')};w.querySelectorAll('.wc-pick').forEach(b=>b.onclick=()=>{inp.value=masters()[type][+b.dataset.i];box.classList.remove('open')});w.querySelectorAll('.wc-del').forEach(b=>b.onclick=e=>{e.stopPropagation();const a=masters()[type],i=+b.dataset.i;if(!confirm(`「${a[i]}」を登録候補から削除しますか？`))return;a.splice(i,1);save();const employeeId=drawer?.dataset?.employeeId;if(employeeId)openEmployee(employeeId,'trabalho')});inp.onfocus=()=>box.classList.add('open');inp.oninput=()=>box.classList.remove('open')})}
 function historyHtml(e){const rows=[...(e.workChangeHistory||[])].sort((a,b)=>new Date(b.date||0)-new Date(a.date||0));return `<div id="workChangeHistory" style="margin-top:20px"><h3 style="margin:0 0 10px">更新歴</h3>${rows.length?rows.map(r=>`<div style="border:1px solid var(--line);border-radius:11px;padding:12px 14px;margin-bottom:8px;background:#fff"><div style="font-weight:700;margin-bottom:7px">${fmtDate(r.date)}</div>${(r.changes||[]).map(c=>`<div><span class="muted">${esc(c.label)}：</span>${esc(c.before||'—')} <span class="muted">→</span> <b>${esc(c.after||'—')}</b></div>`).join('')}</div>`).join(''):'<div class="list-empty">更新履歴はありません。</div>'}</div>`}
 function render(e){const sectors=db.sectors.filter(x=>x.factoryId===e.factoryId),shifts=db.shifts.filter(x=>x.factoryId===e.factoryId),main=drawerBody.querySelector('.employee-detail-main')||drawerBody;main.innerHTML=`<div id="workAlert" style="display:none;margin:0 0 14px;padding:11px 13px;border-radius:10px;background:#fff4f4;border:1px solid #e6aaaa;color:#a22;font-weight:700"></div><div class="hml-bank-card"><div class="hml-bank-head"><div><h3 style="margin:0">勤務情報</h3><div class="muted">所属先・工程・責任者を管理します。</div></div></div><div class="hml-bank-grid">
 <div class="field"><label>社員番号 *</label><div style="display:flex;gap:8px"><input id="workEmpNo" value="${esc(e.empNo||'')}" readonly style="flex:1"><button type="button" class="btn" id="unlockEmpNo">🔒</button></div></div>
 <div class="field"><label>JTEKT社員番号</label><input id="workJtektNo" value="${esc(e.jtektNo||'')}"></div>
 <div class="field"><label>工場 *</label><select id="workFactory">${opt(db.factories,e.factoryId)}</select></div>
 <div class="field"><label>部署</label><select id="workSector">${opt(sectors,e.sectorId)}</select></div>
 <div class="field"><label>所属続き</label><input id="workAffiliationSuffix" value="${esc(e.affiliationSuffix||'')}" placeholder="例：出荷係"></div>
 <div class="field"><label>班</label><select id="workShift">${opt(shifts,e.shiftId)}</select></div>
 <div class="field"><label>工程</label><input id="workProcess" value="${esc(e.process||'')}"></div>
 <div class="field"><label>派遣元側責任者</label><input id="workContractorManager" value="${esc(e.contractorManager||'')}"></div>
 <div class="field"><label>派遣先側責任者</label><input id="workFactoryManager" value="${esc(e.factoryManager||'')}"></div>
 <div class="field"><label>指揮命令者</label>${contactWidget('workCommander',e.commander||'','commanders')}</div>
 <div class="field"><label>苦情申請先</label>${contactWidget('workComplaintContact',e.complaintContact||'','complaints')}</div>
 </div></div><div id="workInlineMaster"></div>${historyHtml(e)}`;drawerFoot.innerHTML=`<button class="btn" onclick="closeDrawer()">閉じる</button><button class="btn primary" id="saveWorkBtn">保存</button>`;
 const emp=document.getElementById('workEmpNo'),unlock=document.getElementById('unlockEmpNo');unlock.onclick=()=>{emp.readOnly=!emp.readOnly;unlock.textContent=emp.readOnly?'🔒':'🔓';if(!emp.readOnly){emp.focus();emp.select()}};
 const fac=document.getElementById('workFactory'),sec=document.getElementById('workSector'),shi=document.getElementById('workShift');fac.onchange=()=>{if(fac.value==='__add__'){showFactoryForm(e);fac.value=e.factoryId||'';return}refreshDependents(fac.value,'','')};sec.onchange=()=>{if(sec.value==='__add__'){showSectorForm(e,fac.value);sec.value=e.sectorId||''}};shi.onchange=()=>{if(shi.value==='__add__'){showShiftForm(e,fac.value);shi.value=e.shiftId||''}};bindContacts();document.getElementById('saveWorkBtn').onclick=()=>saveWork(e)}
 function values(){return {empNo:document.getElementById('workEmpNo')?.value.trim()||'',jtektNo:document.getElementById('workJtektNo')?.value.trim()||'',factoryId:document.getElementById('workFactory')?.value||'',sectorId:document.getElementById('workSector')?.value||'',affiliationSuffix:document.getElementById('workAffiliationSuffix')?.value.trim()||'',shiftId:document.getElementById('workShift')?.value||'',process:document.getElementById('workProcess')?.value.trim()||'',contractorManager:document.getElementById('workContractorManager')?.value.trim()||'',factoryManager:document.getElementById('workFactoryManager')?.value.trim()||'',commander:document.getElementById('workCommander')?.value.trim()||'',complaintContact:document.getElementById('workComplaintContact')?.value.trim()||''}}
 function collectChanges(e,v){const specs=[['empNo','社員番号',x=>x||'—'],['jtektNo','JTEKT社員番号',x=>x||'—'],['factoryId','工場',x=>nameOf(db.factories,x)],['sectorId','部署',x=>nameOf(db.sectors,x)],['affiliationSuffix','所属続き',x=>x||'—'],['shiftId','班',x=>nameOf(db.shifts,x)],['process','工程',x=>x||'—'],['contractorManager','派遣元側責任者',x=>x||'—'],['factoryManager','派遣先側責任者',x=>x||'—'],['commander','指揮命令者',x=>x||'—'],['complaintContact','苦情申請先',x=>x||'—']];return specs.flatMap(([k,l,show])=>{const before=e[k]||'',after=v[k]==='__add__'?'':v[k];return before===after?[]:[{label:l,before:show(before),after:show(after)}]})}
 function saveWork(e){const v=values();if(!v.empNo)return alertWork('社員番号を入力してください。');if(db.employees.some(x=>x.id!==e.id&&x.empNo===v.empNo))return alertWork('この社員番号は既に使用されています。');if(!v.factoryId||v.factoryId==='__add__')return alertWork('工場を選択してください。');const changes=collectChanges(e,v);Object.assign(e,{...v,factoryId:v.factoryId,sectorId:v.sectorId==='__add__'?'':v.sectorId,shiftId:v.shiftId==='__add__'?'':v.shiftId});delete e.work;const m=masters();if(v.commander&&!m.commanders.includes(v.commander))m.commanders.push(v.commander);if(v.complaintContact&&!m.complaints.includes(v.complaintContact))m.complaints.push(v.complaintContact);if(changes.length){const now=new Date().toISOString();e.workChangeHistory=e.workChangeHistory||[];e.workChangeHistory.push({id:uid('wch'),date:now,changes});e.history=e.history||[];e.history.push({date:now,text:'勤務情報を更新'});e.updatedAt=now;e.updatedText='勤務情報を更新'}save();openEmployee(e.id,'trabalho');if(typeof showSavedStatus==='function')showSavedStatus()}
 function refreshDependents(fid,sectorSel='',shiftSel=''){const sec=document.getElementById('workSector'),shi=document.getElementById('workShift');if(!sec||!shi)return;sec.innerHTML=opt(db.sectors.filter(x=>x.factoryId===fid),sectorSel);shi.innerHTML=opt(db.shifts.filter(x=>x.factoryId===fid),shiftSel)}
 function panel(title,body,onSave){const host=document.getElementById('workInlineMaster');host.innerHTML=`<div class="hml-bank-card" style="background:#f8fbff"><div class="hml-bank-head"><h3 style="margin:0">${title}</h3><button class="btn" id="cancelInlineWork">キャンセル</button></div><div class="hml-bank-grid">${body}</div><div style="display:flex;justify-content:flex-end;margin-top:8px"><button class="btn primary" id="saveInlineWork">登録</button></div></div>`;document.getElementById('cancelInlineWork').onclick=()=>host.innerHTML='';document.getElementById('saveInlineWork').onclick=onSave}
 function showFactoryForm(){panel('新しい工場を登録',`<div class="field"><label>取引先 *</label><select id="newFactoryClient"><option value="">—</option>${db.clients.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>工場名 *</label><input id="newFactoryName"></div><div class="field"><label>略称コード</label><input id="newFactoryCode"></div>`,()=>{const clientId=document.getElementById('newFactoryClient').value,name=document.getElementById('newFactoryName').value.trim(),code=document.getElementById('newFactoryCode').value.trim();if(!clientId||!name)return alertWork('取引先と工場名を入力してください。');const f={id:uid('f'),clientId,name,code};db.factories.push(f);save();document.getElementById('workFactory').innerHTML=opt(db.factories,f.id);document.getElementById('workFactory').value=f.id;refreshDependents(f.id);document.getElementById('workInlineMaster').innerHTML=''})}
 function showSectorForm(e,fid){if(!fid)return alertWork('先に工場を選択してください。');panel('新しい部署を登録',`<div class="field"><label>部署名 *</label><input id="newSectorName"></div>`,()=>{const name=document.getElementById('newSectorName').value.trim();if(!name)return alertWork('部署名を入力してください。');const s={id:uid('s'),factoryId:fid,name};db.sectors.push(s);save();refreshDependents(fid,s.id,document.getElementById('workShift')?.value||'');document.getElementById('workSector').value=s.id;document.getElementById('workInlineMaster').innerHTML=''})}
 function showShiftForm(e,fid){if(!fid)return alertWork('先に工場を選択してください。');panel('新しい班を登録',`<div class="field"><label>班名 *</label><input id="newShiftName"></div><div class="field"><label>昼勤開始</label><input type="time" id="newDayStart"></div><div class="field"><label>昼勤終了</label><input type="time" id="newDayEnd"></div><div class="field"><label>夜勤開始</label><input type="time" id="newNightStart"></div><div class="field"><label>夜勤終了</label><input type="time" id="newNightEnd"></div>`,()=>{const name=document.getElementById('newShiftName').value.trim();if(!name)return alertWork('班名を入力してください。');const s={id:uid('b'),factoryId:fid,name,dayStart:document.getElementById('newDayStart').value,dayEnd:document.getElementById('newDayEnd').value,nightStart:document.getElementById('newNightStart').value,nightEnd:document.getElementById('newNightEnd').value};db.shifts.push(s);save();refreshDependents(fid,document.getElementById('workSector')?.value||'',s.id);document.getElementById('workShift').value=s.id;document.getElementById('workInlineMaster').innerHTML=''})}
 function alertWork(msg){const a=document.getElementById('workAlert');if(a){a.textContent=msg;a.style.display='block'}return false}
 if(!document.getElementById('workFinalCss')){const s=document.createElement('style');s.id='workFinalCss';s.textContent=`.wc-wrap{position:relative}.wc-input{padding-right:38px!important}.wc-arrow{position:absolute;right:10px;top:50%;transform:translateY(-50%);border:0;background:transparent;color:#667085;cursor:pointer}.wc-list{display:none;position:absolute;z-index:10020;left:0;right:0;top:calc(100% + 5px);background:#fff;border:1px solid var(--line);border-radius:12px;box-shadow:0 10px 28px #1f29371f;padding:6px;max-height:220px;overflow:auto}.wc-list.open{display:block}.wc-row{display:flex;align-items:center;gap:6px}.wc-pick{flex:1;text-align:left;border:0;background:transparent;padding:9px 10px;border-radius:8px;cursor:pointer}.wc-del{width:30px;height:30px;border:0;background:transparent;cursor:pointer}.wc-empty{padding:9px 10px;color:#8a94a3;font-size:13px}`;document.head.appendChild(s)}
 document.addEventListener('click',()=>document.querySelectorAll('.wc-list.open').forEach(x=>x.classList.remove('open')));
 const base=openEmployee;openEmployee=function(id,tab='dados'){base(id,tab);if(tab==='trabalho'){const e=by(db.employees,id);if(e)render(e)}};
 };wait();
})();